#Author : Chapizze
FROM chapizze/llama:1.1

WORKDIR /llama.cpp

EXPOSE 8888

CMD ./build/bin/llama-server --api-key foobar -m models/Llama-3.1-Tulu-3-8B-Q6_K.gguf -ngl 0 -a llama --host 0.0.0.0 --port 8888 -c 8192 -np 1 -b 512 