FROM node:22

RUN mkdir -p /app
WORKDIR /app
COPY package*.json ./
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libcairo2-dev \
    libpango1.0-dev \
    libjpeg-dev \
    libgif-dev \
    libpixman-1-dev \
    libpangomm-1.4-dev \
    libfreetype6-dev \
    python3 \
    git
RUN npm install
COPY . .
ENV NODE_ENV dev
ENV NODE_ICU_DATA=node_modules/full-icu
ENTRYPOINT [ "npm", "run", "dev"]